# Realización del álgebra de lie $su(1,1)$ en el espacio de Hilbert $L^2(SU(1,1), dg)$

## Determinación del Jacobiano en la parametrización $(\theta, t, \phi)$

In [2]:
using SymPy

# Define the symbolic variables
#@syms θ t ϕ::real
θ,t,ϕ = symbols("θ, t, ϕ", real=true)

(θ, t, ϕ)

In [27]:
function comutator(A,B)
    return A*B-B*A
end

comutator (generic function with 1 method)

In [28]:
H=-Sym[1/2 0; 0 -1/2]

2×2 Matrix{Sym{PyCall.PyObject}}:
 -0.500000000000000                  0
                  0  0.500000000000000

In [29]:
p = -Sym[0 1; 0 0]

2×2 Matrix{Sym{PyCall.PyObject}}:
 0  -1
 0   0

In [30]:
m = Sym[0 0; 1 0]

2×2 Matrix{Sym}:
 0  0
 1  0

### Elementos del  álgebra $T_0, \; T_1,\; T_2$

In [3]:
T_0 = Sym[im/2 0; 0 -im/2]

2×2 Matrix{Sym}:
 0.5⋅ⅈ       0
     0  -0.5⋅ⅈ

In [4]:
T_1 = Sym[0 1/2; 1/2 0]

2×2 Matrix{Sym}:
                 0  0.500000000000000
 0.500000000000000                  0

In [5]:
T_2 = Sym[0 im/2; -im/2 0]

2×2 Matrix{Sym}:
      0  0.5⋅ⅈ
 -0.5⋅ⅈ      0

In [20]:
casimir = T_0^2 - T_1^2 - T_2^2

2×2 Matrix{Sym{PyCall.PyObject}}:
 -0.750000000000000                   0
                  0  -0.750000000000000

### Elementos del álgebra en la forma $j_k=iT_k$

In [12]:
J_0 = im*T_0

2×2 Matrix{Sym{PyCall.PyObject}}:
 -0.500000000000000                  0
                  0  0.500000000000000

In [11]:
J_1  = -im*T_2

2×2 Matrix{Sym{PyCall.PyObject}}:
                  0  0.500000000000000
 -0.500000000000000                  0

In [10]:
J_2 = im*T_1

2×2 Matrix{Sym{PyCall.PyObject}}:
     0  0.5⋅ⅈ
 0.5⋅ⅈ      0

In [27]:
casmir_phy = +J_0^2 +J_0 -(J_1-im*J_2)*(J_1+im*J_2)

2×2 Matrix{Sym{PyCall.PyObject}}:
 0.750000000000000                  0
                 0  0.750000000000000

In [22]:
cas = J_0^2-J_1^2-J_2^2 

2×2 Matrix{Sym{PyCall.PyObject}}:
 0.750000000000000                  0
                 0  0.750000000000000

In [25]:
ca=J_0^2-(1/2)*((J_1+im*J_2)*(J_1-im*J_2)+(J_1-im*J_2)*(J_1+im*J_2))

2×2 Matrix{Sym{PyCall.PyObject}}:
 0.750000000000000                  0
                 0  0.750000000000000

### $M=M(\theta, t, \phi)=K(\theta)A(t)K(\phi)$

In [87]:
#Definir parametrización del grupo 
A = simplify.(exp(-im*t*J_1))

2×2 Matrix{Sym{PyCall.PyObject}}:
   1.0⋅cosh(0.5⋅t)  -1.0⋅ⅈ⋅sinh(0.5⋅t)
 1.0⋅ⅈ⋅sinh(0.5⋅t)     1.0⋅cosh(0.5⋅t)

In [88]:
B = simplify.(exp(-im*t*J_2))

2×2 Matrix{Sym{PyCall.PyObject}}:
 1.0⋅cosh(0.5⋅t)  1.0⋅sinh(0.5⋅t)
 1.0⋅sinh(0.5⋅t)  1.0⋅cosh(0.5⋅t)

In [89]:
K_1 =exp(-im*θ*J_0)

2×2 Matrix{Sym{PyCall.PyObject}}:
 1.0*exp(0.5*I*θ)                  0
                0  1.0*exp(-0.5*I*θ)

In [90]:
K_2 =exp(-im*ϕ*J_0)

2×2 Matrix{Sym{PyCall.PyObject}}:
 1.0*exp(0.5*I*ϕ)                  0
                0  1.0*exp(-0.5*I*ϕ)

In [91]:
M=simplify(K_1*B*K_2)

2×2 Matrix{Sym{PyCall.PyObject}}:
  1.0*exp(0.5*I*θ)*exp(0.5*I*ϕ)*cosh(0.5*t)  …   1.0*exp(0.5*I*θ)*exp(-0.5*I*ϕ)*sinh(0.5*t)
 1.0*exp(-0.5*I*θ)*exp(0.5*I*ϕ)*sinh(0.5*t)     1.0*exp(-0.5*I*θ)*exp(-0.5*I*ϕ)*cosh(0.5*t)

### $g^{-1}\frac{\partial g}{\partial q_k}$

In [68]:
# Calculo de las matrices $g^{-1} \frac{\partial g}{\partial q_k}$ 
function J_component_left(M,k)
    M_inverse = simplify.(M^(-1))
    derivative = simplify.(diff.(M,k))
    return simplify.(M_inverse*derivative)
end

J_component_left (generic function with 1 method)

In [92]:
J_θ_left = J_component_left(M,θ)

2×2 Matrix{Sym{PyCall.PyObject}}:
               0.5⋅ⅈ⋅cosh(1.0⋅t)  0.5*I*exp(-1.0*I*ϕ)*sinh(1.0*t)
 -0.5*I*exp(1.0*I*ϕ)*sinh(1.0*t)               -0.5⋅ⅈ⋅cosh(1.0⋅t)

In [93]:
J_t_left = J_component_left(M,t)

2×2 Matrix{Sym{PyCall.PyObject}}:
                0  0.5*exp(-1.0*I*ϕ)
 0.5*exp(1.0*I*ϕ)                  0

In [94]:
J_ϕ_left = J_component_left(M,ϕ)

2×2 Matrix{Sym{PyCall.PyObject}}:
 0.5⋅ⅈ       0
     0  -0.5⋅ⅈ

Lo anterior se puede hacer de forma manual como sigue 

$A=g^{-1}\frac{\partial g}{\partial \theta}$ donde $\frac{\partial g}{\partial \theta}=T_0 g$

$B=g^{-1}\frac{\partial g}{\partial t}$ donde $\frac{\partial g}{\partial t}=K(\theta)A(t)T_1K(\phi)$ entonces

$B=(K(\theta)A(t)K(\phi))^{-1}K(\theta)A(t)T_1K(\phi)=K^{-1}(\phi)T_1K(\phi)$

$C=g^{-1}\frac{\partial g}{\partial \phi}$ donde $\frac{\partial g}{\partial \phi}=gT_0$

### $\frac{\partial g}{\partial q_k} g^{-1}$

In [72]:
# Calculo de las matrices $\frac{\partial g}{\partial q_k} g^{-1} $ 
function J_component_right(M,k)
    M_inverse = simplify.(M^(-1))
    derivative = simplify.(diff.(M,k))
    return simplify.(derivative*M_inverse)
end

J_component_right (generic function with 1 method)

In [95]:
J_θ_right = J_component_right(M,θ)

2×2 Matrix{Sym{PyCall.PyObject}}:
 0.5⋅ⅈ       0
     0  -0.5⋅ⅈ

In [96]:
J_t_right = J_component_right(M,t)

2×2 Matrix{Sym{PyCall.PyObject}}:
                 0  0.5*exp(1.0*I*θ)
 0.5*exp(-1.0*I*θ)                 0

In [97]:
J_ϕ_right = J_component_right(M,ϕ)

2×2 Matrix{Sym{PyCall.PyObject}}:
               0.5⋅ⅈ⋅cosh(1.0⋅t)  -0.5*I*exp(1.0*I*θ)*sinh(1.0*t)
 0.5*I*exp(-1.0*I*θ)*sinh(1.0*t)               -0.5⋅ⅈ⋅cosh(1.0⋅t)

### Definir el producto interno como $(A,B) = 2 \; Tr(A^{\dagger} B)$

In [99]:
using LinearAlgebra
#Definir producto interno
function inner_product(a,b)
    return 2*tr(a'*b)
end

inner_product (generic function with 1 method)

### Definir la matriz jacobiana como $(J_l)_{jk}=(J_j, ig^{-1}\frac{\partial g}{\partial q_k})$

In [51]:
basis = Dict(1 => J_0, 2 => J_1, 3 => J_2)

#Definir matriz jacobiana
function jacobian(n,derivatives)
    J = zeros(Sym, n, n)
    for i in 1:n
        for j in 1:n
            J[i,j] = inner_product(basis[i],im*derivatives[j])
        end
    end
    return simplify.(J)
end

jacobian (generic function with 1 method)

In [76]:
derivatives_left = Dict(1 => J_θ_left, 2 => J_t_left, 3 => J_ϕ_left)
Jacobian_left = jacobian(3,derivatives_left)

3×3 Matrix{Sym{PyCall.PyObject}}:
             1.0⋅cosh(1.0⋅t)               0  1.00000000000000
 -1.0⋅cos(1.0⋅ϕ)⋅sinh(1.0⋅t)  1.0⋅sin(1.0⋅ϕ)                 0
  1.0⋅sin(1.0⋅ϕ)⋅sinh(1.0⋅t)  1.0⋅cos(1.0⋅ϕ)                 0

### Definir la matriz jacobiana como $(J_r)_{jk}=(J_j, i\frac{\partial g}{\partial q_k}g^{-1})$

In [78]:
derivatives_right = Dict(1 => J_θ_right, 2 => J_t_right, 3 => J_ϕ_right)
Jacobian_right = jacobian(3,derivatives_right)

3×3 Matrix{Sym{PyCall.PyObject}}:
 1.00000000000000                0             1.0⋅cosh(1.0⋅t)
                0  -1.0⋅sin(1.0⋅θ)  1.0⋅cos(1.0⋅θ)⋅sinh(1.0⋅t)
                0   1.0⋅cos(1.0⋅θ)  1.0⋅sin(1.0⋅θ)⋅sinh(1.0⋅t)

### Determinnante de la matriz jacobiana 

In [79]:
d_left = simplify(det(Jacobian_left))

-1.0⋅sinh(1.0⋅t)

In [80]:
d_right = simplify(det(Jacobian_right))

-1.0⋅sinh(1.0⋅t)

## Realización

In [56]:
d_dθ, d_dt, d_dϕ = symbols("∂/∂θ ∂/∂t ∂/∂ϕ")

(∂/∂θ, ∂/∂t, ∂/∂ϕ)

In [57]:
nabla = [d_dθ, d_dt, d_dϕ]

3-element Vector{Sym{PyCall.PyObject}}:
 ∂/∂θ
 ∂/∂t
 ∂/∂ϕ

In [81]:
J_inverse_left=simplify.(Jacobian_left^(-1))

3×3 Matrix{Sym{PyCall.PyObject}}:
 0  -1.0*cos(1.0*ϕ)/sinh(1.0*t)   1.0*sin(1.0*ϕ)/sinh(1.0*t)
 0               1.0⋅sin(1.0⋅ϕ)               1.0⋅cos(1.0⋅ϕ)
 1   1.0*cos(1.0*ϕ)/tanh(1.0*t)  -1.0*sin(1.0*ϕ)/tanh(1.0*t)

In [82]:
J_inverse_right=simplify.(Jacobian_right^(-1))

3×3 Matrix{Sym{PyCall.PyObject}}:
 1  -1.0*cos(1.0*θ)/tanh(1.0*t)  -1.0*sin(1.0*θ)/tanh(1.0*t)
 0              -1.0⋅sin(1.0⋅θ)               1.0⋅cos(1.0⋅θ)
 0   1.0*cos(1.0*θ)/sinh(1.0*t)   1.0*sin(1.0*θ)/sinh(1.0*t)

In [83]:
J_left_inverse_traspose=simplify.(transpose(Jacobian_left^(-1)))

3×3 Matrix{Sym{PyCall.PyObject}}:
                           0               0                            1
 -1.0*cos(1.0*ϕ)/sinh(1.0*t)  1.0⋅sin(1.0⋅ϕ)   1.0*cos(1.0*ϕ)/tanh(1.0*t)
  1.0*sin(1.0*ϕ)/sinh(1.0*t)  1.0⋅cos(1.0⋅ϕ)  -1.0*sin(1.0*ϕ)/tanh(1.0*t)

In [84]:
J_right_inverse_traspose=simplify.(transpose(Jacobian_right^(-1)))

3×3 Matrix{Sym{PyCall.PyObject}}:
                           1                0                           0
 -1.0*cos(1.0*θ)/tanh(1.0*t)  -1.0⋅sin(1.0⋅θ)  1.0*cos(1.0*θ)/sinh(1.0*t)
 -1.0*sin(1.0*θ)/tanh(1.0*t)   1.0⋅cos(1.0⋅θ)  1.0*sin(1.0*θ)/sinh(1.0*t)

In [85]:
left_representation =im*J_left_inverse_traspose*nabla

3-element Vector{Sym{PyCall.PyObject}}:
                                                                                        ⅈ⋅∂/∂ϕ
 1.0*I*∂/∂t*sin(1.0*ϕ) - 1.0*I*∂/∂θ*cos(1.0*ϕ)/sinh(1.0*t) + 1.0*I*∂/∂ϕ*cos(1.0*ϕ)/tanh(1.0*t)
 1.0*I*∂/∂t*cos(1.0*ϕ) + 1.0*I*∂/∂θ*sin(1.0*ϕ)/sinh(1.0*t) - 1.0*I*∂/∂ϕ*sin(1.0*ϕ)/tanh(1.0*t)

In [86]:
right_representation =-im*J_right_inverse_traspose*nabla

3-element Vector{Sym{PyCall.PyObject}}:
                                                                                        -ⅈ⋅∂/∂θ
  1.0*I*∂/∂t*sin(1.0*θ) + 1.0*I*∂/∂θ*cos(1.0*θ)/tanh(1.0*t) - 1.0*I*∂/∂ϕ*cos(1.0*θ)/sinh(1.0*t)
 -1.0*I*∂/∂t*cos(1.0*θ) + 1.0*I*∂/∂θ*sin(1.0*θ)/tanh(1.0*t) - 1.0*I*∂/∂ϕ*sin(1.0*θ)/sinh(1.0*t)

In [64]:
pi_J_1 = left_representation[2]

                        1.0⋅ⅈ⋅∂/∂θ⋅sin(1.0⋅ϕ)   1.0⋅ⅈ⋅∂/∂ϕ⋅sin(1.0⋅ϕ)
1.0⋅ⅈ⋅∂/∂t⋅cos(1.0⋅ϕ) + ───────────────────── - ─────────────────────
                             sinh(1.0⋅t)             tanh(1.0⋅t)     

In [65]:
pi_J_2 = left_representation[3]

                         1.0⋅ⅈ⋅∂/∂θ⋅cos(1.0⋅ϕ)   1.0⋅ⅈ⋅∂/∂ϕ⋅cos(1.0⋅ϕ)
-1.0⋅ⅈ⋅∂/∂t⋅sin(1.0⋅ϕ) + ───────────────────── - ─────────────────────
                              sinh(1.0⋅t)             tanh(1.0⋅t)     