Determinación del Jacobiano en la parametrización $M=M(\theta, t, \phi)=K(\theta)A(t)K(\phi)$

Elementos del  álgebra

In [2]:
T_0 = Sym[im/2 0; 0 -im/2]

2×2 Matrix{Sym}:
 0.5⋅ⅈ       0
     0  -0.5⋅ⅈ

In [3]:
T_1 = Sym[0 1/2; 1/2 0]

2×2 Matrix{Sym}:
                 0  0.500000000000000
 0.500000000000000                  0

In [4]:
T_2 = Sym[0 im/2; -im/2 0]

2×2 Matrix{Sym}:
      0  0.5⋅ⅈ
 -0.5⋅ⅈ      0

$g^{-1}\frac{\partial g}{\partial q_k}$

$A=g^{-1}\frac{\partial g}{\partial \theta}$ donde $\frac{\partial g}{\partial \theta}=T_0 g$

In [ ]:
using SymPy

# Define the symbolic variables
@syms θ t ϕ

# Define the symbolic functions
A = Sym[im*cosh(t)/2 im*exp(-im*ϕ)*sinh(t)/2; -im*exp(im*ϕ)*sinh(t)/2 -im*cosh(t)/2]

2×2 Matrix{Sym}:
           I*cosh(t)/2  I*exp(-I*ϕ)*sinh(t)/2
 -I*exp(I*ϕ)*sinh(t)/2           -I*cosh(t)/2

$B=g^{-1}\frac{\partial g}{\partial \phi}$ donde $\frac{\partial g}{\partial \phi}=gT_0$

In [6]:
B = T_0

2×2 Matrix{Sym}:
 0.5⋅ⅈ       0
     0  -0.5⋅ⅈ

$C=g^{-1}\frac{\partial g}{\partial t}$ donde $\frac{\partial g}{\partial t}=K(\theta)A(t)T_1K(\phi)$ entonces

$C=(K(\theta)A(t)K(\phi))^{-1}K(\theta)A(t)T_1K(\phi)=K^{-1}(\phi)T_1K(\phi)$

In [7]:
C = Sym[0 exp(-im*ϕ)/2; exp(im*ϕ)/2 0]

2×2 Matrix{Sym}:
          0  exp(-I*ϕ)/2
 exp(I*ϕ)/2            0

Definir el producto interno como $(A,B) = 2 \; Tr(A B^{\dagger})$

In [25]:
using LinearAlgebra
#Definir producto interno
function inner_product(a,b)
    return 2*tr(a*b')
end

inner_product (generic function with 1 method)

In [44]:
basis = Dict(1 => T_0, 2 => T_1, 3 => T_2)
derivatives = Dict(1 => A, 2 => C, 3 => B)

#Definir matriz jacobiana
function jacobian(n)
    J = zeros(Sym, n, n)
    for i in 1:3
        for j in 1:3
            J[i,j] = inner_product(derivatives[i],basis[j])
        end
    end
    return J
end

jacobian (generic function with 2 methods)

In [47]:
J = jacobian(3)

3×3 Matrix{Sym}:
      1.0⋅cosh(t)  …  0.5*exp(I*ϕ)*sinh(t) + 0.5*exp(-I*ϕ)*sinh(t)
                0                 0.5*I*exp(I*ϕ) - 0.5*I*exp(-I*ϕ)
 1.00000000000000                                                0

In [48]:
d = det(jacobian(3))

-1.0⋅sinh(t)

In [76]:
# Create the symbolic gradient vector
nabla = [Sym("d/dθ"), Sym("d/dt"), Sym("d/dϕ")]



3-element Vector{Sym{PyCall.PyObject}}:
 d/dθ
 d/dt
 d/dϕ

In [71]:
function simplify_jacobian(J)
    for i in 1:3
        for j in 1:3
            J[i,j] = simplify(J[i,j])
        end
    end
    return J
    
end

J_s=simplify_jacobian(J)

3×3 Matrix{Sym}:
      1.0⋅cosh(t)  1.0⋅sin(ϕ)⋅sinh(t)  1.0⋅cos(ϕ)⋅sinh(t)
                0          1.0⋅cos(ϕ)         -1.0⋅sin(ϕ)
 1.00000000000000                   0                   0

In [73]:
J_s_inverse=simplify_jacobian(J^(-1))

3×3 Matrix{Sym{PyCall.PyObject}}:
                  0            0     1.00000000000000
 1.0*sin(ϕ)/sinh(t)   1.0⋅cos(ϕ)  -1.0*sin(ϕ)/tanh(t)
 1.0*cos(ϕ)/sinh(t)  -1.0⋅sin(ϕ)  -1.0*cos(ϕ)/tanh(t)

In [74]:
representation = J_s_inverse*nabla

3-element Vector{Sym{PyCall.PyObject}}:
                                                             1.0⋅d/dϕ
  1.0*d/dt*cos(ϕ) + 1.0*d/dθ*sin(ϕ)/sinh(t) - 1.0*d/dϕ*sin(ϕ)/tanh(t)
 -1.0*d/dt*sin(ϕ) + 1.0*d/dθ*cos(ϕ)/sinh(t) - 1.0*d/dϕ*cos(ϕ)/tanh(t)